services:
  oceanstor-simulator:
    build: .
    container_name: oceanstor-simulator
    network_mode: host
    environment:
      - OCEANSTOR_POOL=OpenStack_Pool
      - OCEANSTOR_TARGET_IP=192.168.165.1
    volumes:
      - oceanstor-volumes:/app/volumes
    restart: unless-stopped

volumes:
  oceanstor-volumes:
